#pragma once
#ifndef WEAPON_H
#define WEAPON_H

#include <wtypes.h>

typedef enum tagWeaponType
{
	WPT_FIRST = 0,
	WPT_MELEE,
	WPT_HANDGUN,
	WPT_SMG,
	WPT_SHOTGUN,
	WPT_RIFLE,
	WPT_MG,
	WPT_SNIPER,
	WPT_HEAVY,
	WPT_THROWN,
	WPT_LAST
} WeaponType;

typedef enum tagWeaponId
{
	W_FIRST = 0,

	// MELEE
	W_KNIFE,
	W_NIGHTSTICK,
	W_HAMMER,
	W_BAT,
	W_GOLFCLUB,
	W_CROWBAR,
	W_MACHETE,
	W_SWITCHBLADE,
	W_BATTLEAXE,
	W_STONE_HATCHET,

	// HANDGUNS
	W_PISTOL,
	W_PISTOL2,           // Mk II
	W_COMBAT_PISTOL,
	W_AP_PISTOL,
	W_STUN_GUN,
	W_PISTOL50,
	W_SNS_PISTOL,
	W_SNS_PISTOL2,       // Mk II
	W_HEAVY_PISTOL,
	W_VINTAGE_PISTOL,
	W_MARKSMAN_PISTOL,
	W_REVOLVER,
	W_REVOLVER2,         // Mk II
	W_UP_N_ATOMIZER,

	// SMG
	W_MICRO_SMG,
	W_SMG,
	W_SMG2,              // Mk II
	W_ASSAULT_SMG,
	W_COMBAT_PDW,
	W_MACHINE_PISTOL,
	W_MINI_SMG,
	W_TACTICAL_SMG,

	// SHOTGUNS
	W_PUMP_SHOTGUN,
	W_PUMP_SHOTGUN2,     // Mk II
	W_SAWEDOFF_SHOTGUN,
	W_ASSAULT_SHOTGUN,
	W_BULLPUP_SHOTGUN,
	W_HEAVY_SHOTGUN,
	W_DOUBLEBARREL_SHOTGUN,
	W_SWEEPER_SHOTGUN,

	// RIFLES
	W_ASSAULT_RIFLE,
	W_ASSAULT_RIFLE2,    // Mk II
	W_CARBINE_RIFLE,
	W_CARBINE_RIFLE2,    // Mk II
	W_ADVANCED_RIFLE,
	W_SPECIAL_CARBINE,
	W_SPECIAL_CARBINE2,  // Mk II
	W_BULLPUP_RIFLE,
	W_BULLPUP_RIFLE2,    // Mk II
	W_COMPACT_RIFLE,
	W_MILITARY_RIFLE,
	W_HEAVY_RIFLE,
	W_SERVICE_RIFLE,

	// MG
	W_MG,
	W_COMBAT_MG,
	W_COMBAT_MG2,        // Mk II
	W_GUSENBERG,

	// SNIPER
	W_SNIPER_RIFLE,
	W_HEAVY_SNIPER,
	W_HEAVY_SNIPER2,     // Mk II
	W_MARKSMAN_RIFLE,
	W_MARKSMAN_RIFLE2,   // Mk II
	W_PRECISION_RIFLE,

	// HEAVY
	W_RPG,
	W_GRENADE_LAUNCHER,
	W_MINIGUN,
	W_FIREWORK_LAUNCHER,
	W_HOMING_LAUNCHER,
	W_RAILGUN,
	W_COMPACT_LAUNCHER,
	W_WIDOWMAKER,

	// THROWN
	W_GRENADE,
	W_STICKY_BOMB,
	W_PROXIMITY_MINE,
	W_MOLOTOV,
	W_TEARGAS,
	W_PIPEBOMB,

	W_LAST,
	W_COUNT = W_LAST
} WeaponId;

typedef struct TagWeapon
{
	UINT Id;			// no need for UINT
	WeaponType Type;	// weapon type (pistol, rifle, etc.)
	UINT Capacity;		// ammo in one mag can be > 255 (e. g. minigun has 9999)
	UINT MaxAmmo;		// max ammo can be > 255 (multiple magazines, etc.)

} Weapon, *PWeapon, *WeaponPtr;

#endif